name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/ci.yml"

permissions:
  contents: read

env:
  default_node_version: "lts/*"
  default_pnpm_version: "latest"
  artifact_name: build_${{ github.sha }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  lint-ext:
    needs: build
    name: lint-ext
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact_name }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ${{ env.default_pnpm_version }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.default_node_version}}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: web-ext lint
        run: |
          pnpm run lint:ext
